[general]
live_config_reload = true

[window]
option_as_alt = "Both"

[font]
normal = { family = "FiraCode Nerd Font" }
bold = { family = "FiraCode Nerd Font", style = "Bold" }
italic = { family = "FiraCode Nerd Font", style = "Italic" }
bold_italic = { family = "FiraCode Nerd Font", style = "Bold Italic" }
